import 'dart:convert';
import 'dart:io';

import 'package:buddy/sidekick.dart';
import 'package:flutter_test/flutter_test.dart';

typedef Captured = (SidekickEvent event, String label);

Map<String, dynamic> _base(String cwd, String branch, [String? at]) => {
  'parentUuid': null,
  'isSidechain': false,
  'userType': 'external',
  'cwd': cwd,
  'sessionId': 'aaaa1111-2222-3333-4444-555566667777',
  'version': '2.1.39',
  'gitBranch': branch,
  'timestamp': at ?? DateTime.now().toUtc().toIso8601String(),
  'uuid': 'eec2ece2-79c8-4808-979d-7a27565cb506',
};

String _userLine(String cwd, String branch, Object content, [String? at]) =>
    jsonEncode({
      ..._base(cwd, branch, at),
      'type': 'user',
      'message': {'role': 'user', 'content': content},
    });

String _assistantLine(
  String cwd,
  String branch,
  String text, {
  int cacheRead = 19885,
  String? at,
  String stop = 'end_turn',
}) => jsonEncode({
  ..._base(cwd, branch, at),
  'type': 'assistant',
  'requestId': 'req_011CRJyBmRE2',
  'message': {
    'id': 'msg_01Vv7Z2AbcD',
    'type': 'message',
    'role': 'assistant',
    'model': 'claude-fable-5',
    'content': [
      {'type': 'text', 'text': text},
    ],
    'stop_reason': stop,
    'usage': {
      'input_tokens': 2,
      'cache_creation_input_tokens': 21311,
      'cache_read_input_tokens': cacheRead,
      'output_tokens': 3139,
    },
  },
});

const _header =
    '{"type":"ai-title","aiTitle":"Test session","sessionId":"aaaa1111"}\n'
    '{"type":"mode","mode":"normal","sessionId":"aaaa1111"}\n'
    '{"type":"permission-mode","permissionMode":"default","sessionId":"aaaa1111"}\n'
    '{"type":"file-history-snapshot","messageId":"m1","snapshot":{"messageId":"m1","trackedFileBackups":{},"timestamp":"2026-07-15T08:24:32.703Z"},"isSnapshotUpdate":false}';

String _metaUserLines(String cwd, String branch) => [
  _userLine(
    cwd,
    branch,
    '<local-command-caveat>Caveat: The messages below were generated by the '
    'user while running local commands. DO NOT respond to these messages.'
    '</local-command-caveat>',
  ),
  _userLine(
    cwd,
    branch,
    '<command-name>/model</command-name>\n'
    '            <command-message>model</command-message>',
  ),
  _userLine(
    cwd,
    branch,
    '<local-command-stdout>Set model to Fable 5</local-command-stdout>',
  ),
].join('\n');

String _tailLines(String cwd, String branch, [String? at]) =>
    '${jsonEncode({..._base(cwd, branch, at), 'type': 'system', 'subtype': 'turn_duration', 'durationMs': 12345, 'isMeta': true, 'content': ''})}\n'
    '{"type":"last-prompt","leafUuid":"266e09d0-6ccb-4421-a3f6-86de436d51f1","sessionId":"aaaa1111"}';

String _sessionDoc({
  required String cwd,
  required String branch,
  required String prompt,
  String? firstUserContent,
  String? at,
}) {
  final lines = [
    _header,
    _metaUserLines(cwd, branch),
    if (firstUserContent != null) _userLine(cwd, branch, firstUserContent, at),
    _userLine(cwd, branch, prompt, at),
    _assistantLine(cwd, branch, 'On it.', at: at),
    _userLine(cwd, branch, [
      {'type': 'tool_result', 'tool_use_id': 'toolu_1', 'content': 'ok'},
    ], at),
    _assistantLine(cwd, branch, 'Done.', at: at),
    _tailLines(cwd, branch, at),
  ];
  return '${lines.join('\n')}\n';
}

void main() {
  late Directory tmp;
  late List<Captured> events;

  setUp(() {
    tmp = Directory.systemTemp.createTempSync('sidekick_test');
    events = [];
  });

  tearDown(() {
    tmp.deleteSync(recursive: true);
  });

  void collect(SidekickEvent event, String label) => events.add((event, label));

  Sidekick makeSidekick({
    String? Function()? frontApp,
    Map<String, int>? Function()? liveProbe,
    Duration workingWindow = const Duration(seconds: 15),
    Duration completionQuietMin = const Duration(seconds: 20),
    Duration completionMinRun = const Duration(seconds: 90),
    Duration nagQuietMin = const Duration(seconds: 45),
    Duration nagQuietMax = const Duration(minutes: 10),
    Duration nagMinRun = const Duration(seconds: 10),
  }) => Sidekick(
    collect,
    projectsDirOverride: tmp.path,
    frontAppOverride: frontApp ?? () => null,
    liveProbeOverride: liveProbe,
    announceAfter: const Duration(hours: 1),
    workingWindow: workingWindow,
    completionQuietMin: completionQuietMin,
    completionMinRun: completionMinRun,
    nagQuietMin: nagQuietMin,
    nagQuietMax: nagQuietMax,
    nagMinRun: nagMinRun,
  );

  File writeSession(
    String projectDir,
    String fileName, {
    required String cwd,
    required String branch,
    required String prompt,
    String? firstUserContent,
    String? at,
  }) {
    final dir = Directory('${tmp.path}/$projectDir')
      ..createSync(recursive: true);
    return File('${dir.path}/$fileName')..writeAsStringSync(
      _sessionDoc(
        cwd: cwd,
        branch: branch,
        prompt: prompt,
        firstUserContent: firstUserContent,
        at: at,
      ),
      flush: true,
    );
  }

  List<Captured> ofType(SidekickEvent type) =>
      events.where((e) => e.$1 == type).toList();

  group('completion', () {
    test(
      'fires once for a long run that goes quiet ending in assistant',
      () async {
        final file = writeSession(
          '-Users-t-Desktop-alpha',
          'aaaa1111.jsonl',
          cwd: '/Users/t/Desktop/alpha',
          branch: 'main',
          prompt: 'Fix the login flow',
        );
        final sidekick = makeSidekick(
          completionQuietMin: const Duration(milliseconds: 100),
          completionMinRun: const Duration(milliseconds: 200),
        );
        sidekick.scanOnce();
        expect(sidekick.anyWorking, isTrue);
        await Future<void>.delayed(const Duration(milliseconds: 250));
        file.writeAsStringSync(
          '${_assistantLine('/Users/t/Desktop/alpha', 'main', 'All fixed.')}\n'
          '${_tailLines('/Users/t/Desktop/alpha', 'main')}\n',
          mode: FileMode.append,
          flush: true,
        );
        sidekick.scanOnce();
        await Future<void>.delayed(const Duration(milliseconds: 150));
        sidekick.scanOnce();
        sidekick.scanOnce();
        expect(ofType(SidekickEvent.completed), [
          (SidekickEvent.completed, 'alpha'),
        ]);
        expect(ofType(SidekickEvent.needsInput), isEmpty);
        expect(ofType(SidekickEvent.error), isEmpty);
      },
    );

    test('is not suppressed by a terminal front app', () async {
      final file = writeSession(
        '-Users-t-Desktop-alpha',
        'aaaa1111.jsonl',
        cwd: '/Users/t/Desktop/alpha',
        branch: 'main',
        prompt: 'Fix the login flow',
      );
      final sidekick = makeSidekick(
        frontApp: () => 'Terminal',
        completionQuietMin: const Duration(milliseconds: 100),
        completionMinRun: const Duration(milliseconds: 200),
      );
      sidekick.scanOnce();
      await Future<void>.delayed(const Duration(milliseconds: 250));
      file.writeAsStringSync(
        '${_assistantLine('/Users/t/Desktop/alpha', 'main', 'All fixed.')}\n',
        mode: FileMode.append,
        flush: true,
      );
      sidekick.scanOnce();
      await Future<void>.delayed(const Duration(milliseconds: 150));
      sidekick.scanOnce();
      expect(ofType(SidekickEvent.completed), hasLength(1));
    });
  });

  group('needsInput labels', () {
    Sidekick makeNagSidekick({String? Function()? frontApp}) => makeSidekick(
      frontApp: frontApp,
      nagQuietMin: const Duration(milliseconds: 100),
      nagMinRun: Duration.zero,
    );

    test('single session in a folder uses the folder name only', () async {
      writeSession(
        '-Users-t-Desktop-alpha',
        'aaaa1111.jsonl',
        cwd: '/Users/t/Desktop/alpha',
        branch: 'main',
        prompt: 'Fix the login flow',
      );
      final sidekick = makeNagSidekick();
      sidekick.scanOnce();
      await Future<void>.delayed(const Duration(milliseconds: 150));
      sidekick.scanOnce();
      expect(events, [(SidekickEvent.needsInput, 'alpha')]);
    });

    test(
      'two sessions, same folder, different branches use folder (branch)',
      () async {
        writeSession(
          '-Users-t-Desktop-alpha',
          'aaaa1111.jsonl',
          cwd: '/Users/t/Desktop/alpha',
          branch: 'main',
          prompt: 'Fix the login flow',
        );
        writeSession(
          '-Users-t-Desktop-alpha',
          'bbbb2222.jsonl',
          cwd: '/Users/t/Desktop/alpha',
          branch: 'dev',
          prompt: 'Refactor the cart page',
        );
        final sidekick = makeNagSidekick();
        sidekick.scanOnce();
        await Future<void>.delayed(const Duration(milliseconds: 150));
        sidekick.scanOnce();
        final labels = ofType(
          SidekickEvent.needsInput,
        ).map((e) => e.$2).toSet();
        expect(labels, {'alpha (main)', 'alpha (dev)'});
      },
    );

    test(
      'two sessions, same folder, same branch get positional seats',
      () async {
        writeSession(
          '-Users-t-Desktop-alpha',
          'aaaa1111.jsonl',
          cwd: '/Users/t/Desktop/alpha',
          branch: 'main',
          prompt: 'Fix the login flow',
        );
        writeSession(
          '-Users-t-Desktop-alpha',
          'bbbb2222.jsonl',
          cwd: '/Users/t/Desktop/alpha',
          branch: 'main',
          prompt: 'Refactor the cart page',
        );
        final sidekick = makeNagSidekick();
        sidekick.scanOnce();
        await Future<void>.delayed(const Duration(milliseconds: 150));
        sidekick.scanOnce();
        final labels = ofType(
          SidekickEvent.needsInput,
        ).map((e) => e.$2).toSet();
        expect(labels, {'alpha', 'alpha (2)'});
        expect(labels.any((l) => l.contains('Fix the login flow')), isFalse);
        expect(labels.any((l) => l.contains('Refactor the cart')), isFalse);
      },
    );

    test('is suppressed while a terminal app is frontmost', () async {
      writeSession(
        '-Users-t-Desktop-alpha',
        'aaaa1111.jsonl',
        cwd: '/Users/t/Desktop/alpha',
        branch: 'main',
        prompt: 'Fix the login flow',
      );
      final sidekick = makeNagSidekick(frontApp: () => 'Terminal');
      sidekick.scanOnce();
      await Future<void>.delayed(const Duration(milliseconds: 150));
      sidekick.scanOnce();
      expect(events, isEmpty);
    });
  });

  test('jsonl files below a project directory produce no events', () async {
    const cwd = '/Users/t/Desktop/alpha';
    final deep = Directory(
      '${tmp.path}/-Users-t-Desktop-alpha/'
      'aaaa1111-2222-3333-4444-555566667777/subagents',
    )..createSync(recursive: true);
    final agent = File('${deep.path}/agent-a231911ba5aae5cca.jsonl')
      ..writeAsStringSync(
        _sessionDoc(cwd: cwd, branch: 'main', prompt: 'Build a dashboard'),
        flush: true,
      );
    final workflow = Directory('${deep.path}/workflows/wf_815b6d70-705')
      ..createSync(recursive: true);
    File('${workflow.path}/step-1.jsonl').writeAsStringSync(
      _sessionDoc(cwd: cwd, branch: 'main', prompt: 'Run step one'),
      flush: true,
    );
    final sidekick = makeSidekick(
      completionQuietMin: const Duration(milliseconds: 50),
      completionMinRun: Duration.zero,
      nagQuietMin: const Duration(milliseconds: 50),
      nagMinRun: Duration.zero,
    );
    sidekick.scanOnce();
    await Future<void>.delayed(const Duration(milliseconds: 100));
    agent.writeAsStringSync(
      '${_assistantLine(cwd, 'main', 'Subagent done.')}\n',
      mode: FileMode.append,
      flush: true,
    );
    sidekick.scanOnce();
    await Future<void>.delayed(const Duration(milliseconds: 100));
    sidekick.scanOnce();
    expect(events, isEmpty);
    expect(sidekick.anyWorking, isFalse);
  });

  test('contextLow fires once per climb and re-arms after a compact', () async {
    const cwd = '/Users/t/Desktop/alpha';
    final file = writeSession(
      '-Users-t-Desktop-alpha',
      'aaaa1111.jsonl',
      cwd: cwd,
      branch: 'main',
      prompt: 'Fix the login flow',
    );
    final sidekick = makeSidekick();
    sidekick.scanOnce();
    expect(ofType(SidekickEvent.contextLow), isEmpty);
    file.writeAsStringSync(
      '${_assistantLine(cwd, 'main', 'Big turn.', cacheRead: 150000)}\n',
      mode: FileMode.append,
      flush: true,
    );
    sidekick.scanOnce();
    expect(ofType(SidekickEvent.contextLow), [
      (SidekickEvent.contextLow, 'alpha'),
    ]);
    expect(sidekick.snapshot().single.context, greaterThan(0.7));
    file.writeAsStringSync(
      '${_assistantLine(cwd, 'main', 'Still big.', cacheRead: 156000)}\n',
      mode: FileMode.append,
      flush: true,
    );
    sidekick.scanOnce();
    expect(ofType(SidekickEvent.contextLow), hasLength(1));
    file.writeAsStringSync(
      '${_assistantLine(cwd, 'main', 'Fresh after compact.')}\n',
      mode: FileMode.append,
      flush: true,
    );
    sidekick.scanOnce();
    file.writeAsStringSync(
      '${_assistantLine(cwd, 'main', 'Big again.', cacheRead: 152000)}\n',
      mode: FileMode.append,
      flush: true,
    );
    sidekick.scanOnce();
    expect(ofType(SidekickEvent.contextLow), hasLength(2));
  });

  test('a running tool never reads as done', () async {
    const cwd = '/Users/t/Desktop/alpha';
    final file = writeSession(
      '-Users-t-Desktop-alpha',
      'aaaa1111.jsonl',
      cwd: cwd,
      branch: 'main',
      prompt: 'Fix the login flow',
    );
    final sidekick = makeSidekick(
      completionQuietMin: const Duration(milliseconds: 50),
      completionMinRun: Duration.zero,
      nagQuietMin: const Duration(milliseconds: 50),
      nagMinRun: Duration.zero,
    );
    file.writeAsStringSync(
      '${_assistantLine(cwd, 'main', 'Running the build.', stop: 'tool_use')}\n',
      mode: FileMode.append,
      flush: true,
    );
    sidekick.scanOnce();
    await Future<void>.delayed(const Duration(milliseconds: 150));
    sidekick.scanOnce();
    sidekick.scanOnce();
    expect(ofType(SidekickEvent.completed), isEmpty);
    expect(ofType(SidekickEvent.needsInput), isEmpty);
    expect(sidekick.snapshot().single.state, SessionState.working);
  });

  test('a fresh prompt clears done and completion fires again', () async {
    const cwd = '/Users/t/Desktop/alpha';
    final file = writeSession(
      '-Users-t-Desktop-alpha',
      'aaaa1111.jsonl',
      cwd: cwd,
      branch: 'main',
      prompt: 'Fix the login flow',
    );
    final sidekick = makeSidekick(
      workingWindow: const Duration(milliseconds: 30),
      completionQuietMin: const Duration(milliseconds: 50),
      completionMinRun: Duration.zero,
    );
    sidekick.scanOnce();
    await Future<void>.delayed(const Duration(milliseconds: 100));
    sidekick.scanOnce();
    expect(ofType(SidekickEvent.completed), hasLength(1));
    expect(sidekick.snapshot().single.state, SessionState.done);
    file.writeAsStringSync(
      '${_userLine(cwd, 'main', 'Now also fix signup please')}\n',
      mode: FileMode.append,
      flush: true,
    );
    sidekick.scanOnce();
    expect(sidekick.snapshot().single.state, SessionState.working);
    file.writeAsStringSync(
      '${_assistantLine(cwd, 'main', 'Signup fixed too.')}\n',
      mode: FileMode.append,
      flush: true,
    );
    sidekick.scanOnce();
    await Future<void>.delayed(const Duration(milliseconds: 100));
    sidekick.scanOnce();
    expect(ofType(SidekickEvent.completed), hasLength(2));
  });

  test('a touched but stale transcript stays off the radar', () async {
    final oldStamp = DateTime.now()
        .toUtc()
        .subtract(const Duration(days: 17))
        .toIso8601String();
    writeSession(
      '-Users-t-Desktop-alpha',
      'aaaa1111.jsonl',
      cwd: '/Users/t/Desktop/alpha',
      branch: 'feature-lead-onboarding',
      prompt: 'Build lead onboarding',
      at: oldStamp,
    );
    final sidekick = makeSidekick(
      completionQuietMin: const Duration(milliseconds: 50),
      completionMinRun: Duration.zero,
      nagQuietMin: const Duration(milliseconds: 50),
      nagMinRun: Duration.zero,
    );
    sidekick.scanOnce();
    expect(sidekick.anyWorking, isFalse);
    expect(sidekick.snapshot(), isEmpty);
    await Future<void>.delayed(const Duration(milliseconds: 150));
    sidekick.scanOnce();
    sidekick.scanOnce();
    expect(events, isEmpty);
  });

  test('labels use the newest branch, not the birth branch', () async {
    const cwd = '/Users/t/Desktop/alpha';
    final file = writeSession(
      '-Users-t-Desktop-alpha',
      'aaaa1111.jsonl',
      cwd: cwd,
      branch: 'feature-lead-onboarding',
      prompt: 'Build lead onboarding',
    );
    file.writeAsStringSync(
      '${_assistantLine(cwd, 'main', 'Back on main now.')}\n',
      mode: FileMode.append,
      flush: true,
    );
    writeSession(
      '-Users-t-Desktop-alpha',
      'bbbb2222.jsonl',
      cwd: cwd,
      branch: 'dev',
      prompt: 'Refactor the cart page',
    );
    final sidekick = makeSidekick(
      nagQuietMin: const Duration(milliseconds: 100),
      nagMinRun: Duration.zero,
    );
    sidekick.scanOnce();
    await Future<void>.delayed(const Duration(milliseconds: 150));
    sidekick.scanOnce();
    final labels = ofType(SidekickEvent.needsInput).map((e) => e.$2).toSet();
    expect(labels, {'alpha (main)', 'alpha (dev)'});
  });

  test('a compact boundary resets the context count', () async {
    const cwd = '/Users/t/Desktop/alpha';
    final file = writeSession(
      '-Users-t-Desktop-alpha',
      'aaaa1111.jsonl',
      cwd: cwd,
      branch: 'main',
      prompt: 'Fix the login flow',
    );
    final sidekick = makeSidekick();
    file.writeAsStringSync(
      '${_assistantLine(cwd, 'main', 'Big turn.', cacheRead: 170000)}\n',
      mode: FileMode.append,
      flush: true,
    );
    sidekick.scanOnce();
    expect(ofType(SidekickEvent.contextLow), hasLength(1));
    expect(sidekick.snapshot().single.context, greaterThan(0.7));
    file.writeAsStringSync(
      '${jsonEncode({
        ..._base(cwd, 'main'),
        'type': 'system',
        'subtype': 'compact_boundary',
        'compactMetadata': {'trigger': 'manual', 'preTokens': 195000},
      })}\n',
      mode: FileMode.append,
      flush: true,
    );
    sidekick.scanOnce();
    expect(sidekick.snapshot().single.context, 0);
    expect(ofType(SidekickEvent.contextLow), hasLength(1));
    file.writeAsStringSync(
      '${_assistantLine(cwd, 'main', 'Big again.', cacheRead: 170000)}\n',
      mode: FileMode.append,
      flush: true,
    );
    sidekick.scanOnce();
    expect(ofType(SidekickEvent.contextLow), hasLength(2));
  });

  test('an auto compact boundary teaches the real ceiling', () async {
    const cwd = '/Users/t/Desktop/alpha';
    final file = writeSession(
      '-Users-t-Desktop-alpha',
      'aaaa1111.jsonl',
      cwd: cwd,
      branch: 'main',
      prompt: 'Fix the login flow',
    );
    final sidekick = makeSidekick();
    file.writeAsStringSync(
      '${jsonEncode({
        ..._base(cwd, 'main'),
        'type': 'system',
        'subtype': 'compact_boundary',
        'compactMetadata': {'trigger': 'auto', 'preTokens': 780000},
      })}\n'
      '${_assistantLine(cwd, 'main', 'Fresh.', cacheRead: 200000)}\n',
      mode: FileMode.append,
      flush: true,
    );
    sidekick.scanOnce();
    expect(ofType(SidekickEvent.contextLow), isEmpty);
    file.writeAsStringSync(
      '${_assistantLine(cwd, 'main', 'Huge.', cacheRead: 700000)}\n',
      mode: FileMode.append,
      flush: true,
    );
    sidekick.scanOnce();
    expect(ofType(SidekickEvent.contextLow), hasLength(1));
  });

  test('usage past 200k proves a big window and honest percentages', () async {
    const cwd = '/Users/t/Desktop/alpha';
    final file = writeSession(
      '-Users-t-Desktop-alpha',
      'aaaa1111.jsonl',
      cwd: cwd,
      branch: 'main',
      prompt: 'Fix the login flow',
    );
    file.writeAsStringSync(
      '${_assistantLine(cwd, 'main', 'Deep in it.', cacheRead: 250000)}\n',
      mode: FileMode.append,
      flush: true,
    );
    final sidekick = makeSidekick();
    sidekick.scanOnce();
    expect(ofType(SidekickEvent.contextLow), isEmpty);
    final row = sidekick.snapshot().single;
    expect(row.context, closeTo((2 + 21311 + 250000 + 3139) / 1000000, 0.001));
  });

  test('contextLow waits until the terminal is left', () async {
    const cwd = '/Users/t/Desktop/alpha';
    var front = 'Terminal';
    final file = writeSession(
      '-Users-t-Desktop-alpha',
      'aaaa1111.jsonl',
      cwd: cwd,
      branch: 'main',
      prompt: 'Fix the login flow',
    );
    final sidekick = makeSidekick(frontApp: () => front);
    file.writeAsStringSync(
      '${_assistantLine(cwd, 'main', 'Big turn.', cacheRead: 170000)}\n',
      mode: FileMode.append,
      flush: true,
    );
    sidekick.scanOnce();
    expect(ofType(SidekickEvent.contextLow), isEmpty);
    front = 'Safari';
    file.writeAsStringSync(
      '${_assistantLine(cwd, 'main', 'Still big.', cacheRead: 172000)}\n',
      mode: FileMode.append,
      flush: true,
    );
    sidekick.scanOnce();
    expect(ofType(SidekickEvent.contextLow), hasLength(1));
  });

  group('process liveness', () {
    test('a session in a project with no claude process disappears', () async {
      writeSession(
        '-Users-t-Desktop-alpha',
        'aaaa1111.jsonl',
        cwd: '/Users/t/Desktop/alpha',
        branch: 'main',
        prompt: 'Fix the login flow',
      );
      final sidekick = makeSidekick(
        liveProbe: () => {},
        workingWindow: const Duration(milliseconds: 30),
        nagQuietMin: const Duration(milliseconds: 100),
        nagMinRun: Duration.zero,
      );
      sidekick.scanOnce();
      await Future<void>.delayed(const Duration(milliseconds: 150));
      sidekick.scanOnce();
      expect(sidekick.snapshot(), isEmpty);
      expect(events, isEmpty);
    });

    test('an open but quiet session shows as idle, not vanished', () async {
      writeSession(
        '-Users-t-Desktop-alpha',
        'aaaa1111.jsonl',
        cwd: '/Users/t/Desktop/alpha',
        branch: 'main',
        prompt: 'Fix the login flow',
      );
      final sidekick = makeSidekick(
        liveProbe: () => {'-Users-t-Desktop-alpha': 1},
        workingWindow: const Duration(milliseconds: 30),
        nagQuietMin: const Duration(milliseconds: 50),
        nagQuietMax: const Duration(milliseconds: 50),
      );
      sidekick.scanOnce();
      await Future<void>.delayed(const Duration(milliseconds: 150));
      sidekick.scanOnce();
      expect(sidekick.snapshot().single.state, SessionState.idle);
      expect(events, isEmpty);
    });

    test(
      'a process that exits right after finishing still completes',
      () async {
        const cwd = '/Users/t/Desktop/alpha';
        final file = writeSession(
          '-Users-t-Desktop-alpha',
          'aaaa1111.jsonl',
          cwd: cwd,
          branch: 'main',
          prompt: 'Fix the login flow',
        );
        final sidekick = makeSidekick(
          liveProbe: () => {},
          completionMinRun: const Duration(milliseconds: 200),
        );
        sidekick.scanOnce();
        await Future<void>.delayed(const Duration(milliseconds: 250));
        file.writeAsStringSync(
          '${_assistantLine(cwd, 'main', 'All wrapped.')}\n',
          mode: FileMode.append,
          flush: true,
        );
        sidekick.scanOnce();
        sidekick.scanOnce();
        expect(ofType(SidekickEvent.completed), hasLength(1));
        expect(ofType(SidekickEvent.needsInput), isEmpty);
      },
    );

    test('a live project resurfaces its newest stale transcript', () async {
      final old = DateTime.now().subtract(const Duration(minutes: 20));
      final file = writeSession(
        '-Users-t-Desktop-alpha',
        'aaaa1111.jsonl',
        cwd: '/Users/t/Desktop/alpha',
        branch: 'main',
        prompt: 'Fix the login flow',
        at: old.toUtc().toIso8601String(),
      );
      file.setLastModifiedSync(old);
      final sidekick = makeSidekick(
        liveProbe: () => {'-Users-t-Desktop-alpha': 1},
      );
      sidekick.scanOnce();
      final row = sidekick.snapshot().single;
      expect(row.state, SessionState.idle);
      expect(row.label, 'alpha');
      expect(events, isEmpty);
      final dead = makeSidekick(liveProbe: () => {});
      dead.scanOnce();
      expect(dead.snapshot(), isEmpty);
    });
  });

  test('labels never leak prompt text, whatever the transcript says', () async {
    writeSession(
      '-Users-t-Desktop-alpha',
      'aaaa1111.jsonl',
      cwd: '/Users/t/Desktop/alpha',
      branch: 'main',
      prompt: 'Ship the pantry tab',
      firstUserContent:
          '<system-reminder>\nAs you answer the user\'s questions, you can '
          'use the following context.\n</system-reminder>',
    );
    writeSession(
      '-Users-t-Desktop-alpha',
      'bbbb2222.jsonl',
      cwd: '/Users/t/Desktop/alpha',
      branch: 'main',
      prompt: 'Refactor the cart page',
    );
    final sidekick = makeSidekick(
      nagQuietMin: const Duration(milliseconds: 100),
      nagMinRun: Duration.zero,
    );
    sidekick.scanOnce();
    await Future<void>.delayed(const Duration(milliseconds: 150));
    sidekick.scanOnce();
    final labels = ofType(SidekickEvent.needsInput).map((e) => e.$2).toSet();
    expect(labels, {'alpha', 'alpha (2)'});
    for (final leak in const [
      'Ship the pantry tab',
      'Refactor the cart page',
      'system-reminder',
    ]) {
      expect(labels.any((l) => l.contains(leak)), isFalse, reason: leak);
    }
  });
}
